packet_put: Add missing bug.h include for global_die
```
packet_put.c:53:9: error: call to undeclared function 'global_die'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        global_die(111);
        ^
1 error generated.
```